"""A ``codex`` shim, so the right home is selected without thinking about it.

This is the only point at which the tool inserts itself into the shell. It is
opt-in, it lives in its own directory, and it resolves the real executable by
scanning ``PATH`` while skipping that directory -- so it cannot call itself.
"""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path

from .home import private_dir

MARKER = "# generated by settingfix -- edit nothing here"

POSIX_TEMPLATE = """#!/bin/sh
{marker}
exec "{python}" -m settingfix exec "$@"
"""

WINDOWS_TEMPLATE = """@echo off
rem {marker}
"{python}" -m settingfix exec %*
"""


def shim_dir(store_root: Path) -> Path:
    return store_root / "shim"


def install(store_root: Path, python: str | None = None, name: str = "codex") -> Path:
    folder = private_dir(shim_dir(store_root))
    python = python or sys.executable
    folder.mkdir(parents=True, exist_ok=True)
    if sys.platform.startswith("win"):
        path = folder / f"{name}.cmd"
        path.write_text(WINDOWS_TEMPLATE.format(marker=MARKER, python=python), encoding="utf-8")
    else:
        path = folder / name
        path.write_text(POSIX_TEMPLATE.format(marker=MARKER, python=python), encoding="utf-8")
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


def uninstall(store_root: Path, name: str = "codex") -> list[Path]:
    folder = shim_dir(store_root)
    removed: list[Path] = []
    for candidate in (folder / f"{name}.cmd", folder / name):
        if candidate.is_file() and MARKER in candidate.read_text(encoding="utf-8", errors="replace"):
            candidate.unlink()
            removed.append(candidate)
    if folder.is_dir() and not any(folder.iterdir()):
        folder.rmdir()
    return removed


def on_path(folder: Path) -> bool:
    entries = (Path(p) for p in os.environ.get("PATH", "").split(os.pathsep) if p)
    try:
        wanted = folder.resolve()
    except OSError:
        return False
    for entry in entries:
        try:
            if entry.resolve() == wanted:
                return True
        except OSError:
            continue
    return False
